microservice:
  swagger:
    name: BHC-WS (v1.0)
    description: Bayer-Health-Care REST WEB Service
  oauth2:
    enabled: false # Disable for development only

bhcws:
   #mode: ${BHCWS_MODE}
   #mode: "prod"
   mode: "test"