microservice:
  swagger:
    name: Mibi File Provider
    description: Microbilg File Provider REST Service
  oauth2:
    enabled: false # Disable for development only

mibi:
  filePath: "src/test/resources/pdf"