microservice:
  swagger:
    name: BHC-WS
    description: Bayer-Health-Care REST WEB Service
    version: 1.0
  oauth2:
    enabled: false # Disable for development only

spring:
  datasource:
    url: jdbc:mysql://SHR-QA-DB-01:3306/squid
    platform: h2
    username: devdba
    password: N1xputm8chn!
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
