CREATE TABLE IF NOT EXISTS `Portfolio` (	
	PFL_CLT_ID INT NOT NULL,
	PFL_CDP_ID INT,
	PFL_WRK_ID INT NOT NULL,
	PFL_CUST_ID VARCHAR(20) NOT NULL,
	PFL_DTT_ID INT NOT NULL,
	PFL_COUNTRY_ISO3 VARCHAR(20) NOT NULL,
	PFL_CURRENCY_ISO3 VARCHAR(20) NOT NULL,
	PFL_LEDGER_KEY VARCHAR(20) NOT NULL,
	PFL_START_DATE DATETIME NOT NULL,
	PFL_END_DATE DATETIME,
	PRIMARY KEY (PFL_CLT_ID)
);

DELETE FROM `Portfolio`;

INSERT INTO `Portfolio` (PFL_CLT_ID, PFL_CDP_ID, PFL_WRK_ID, PFL_CUST_ID, PFL_DTT_ID, PFL_COUNTRY_ISO3, PFL_CURRENCY_ISO3, PFL_LEDGER_KEY, PFL_START_DATE, PFL_END_DATE) VALUES
	                     (1, 123, 1, '111', 2, 'DE', 'EUR', 'SQUID', '2016-01-07', NULL),
	                     (2, 123, 2, '222', 1, 'DE', 'EUR', 'SQUID', '2016-01-07', '2016-01-09'),
	                     (3, 111, 3, '333', 2, 'DE', 'EUR', 'SQUID', '2016-01-01', '2016-01-03'),
	                     (5, 123, 4, '444', 3, 'SE', 'SWK', 'SQUID', '2016-01-03', '2016-01-10');

CREATE TABLE IF NOT EXISTS `Workflow` (	
	WRK_ID INT NOT NULL,
	WRK_CLT_ID INT NOT NULL,
	WRK_CDP_ID VARCHAR(50),
	WRK_TYPE_CD VARCHAR(1),
	WRK_TODO_ID VARCHAR(20),
	WRK_START_DATE DATETIME NOT NULL,
	WRK_END_DATE DATETIME,
	PRIMARY KEY (WRK_ID)
);
DELETE FROM `Workflow`;



	

